# Dockerfile.nginx
FROM nginx:latest
WORKDIR /app

# Install necessary tools for debugging
RUN apt-get update && apt-get install -y net-tools iputils-ping curl

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy Nginx config
COPY default.conf /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]
