# Dockerfile.nginx
FROM nginx:latest
WORKDIR /app

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy Nginx config
COPY nginx.conf /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]
